Add form component, createPage and localStorage.
roscha80/capstone-project pull request #7
Opened 2021-06-14 08:09 UTC by roscha80

2021-06-14 09:23 UTC, macfrei requested changes
Hi Rob! Looks great, I added a few suggestions though! Keep it going 🚀

2021-06-14 09:23 UTC, macfrei commented on src/App.js
> +import useLocalStorage from './sort/useLocalStorage'
`sort` is that a folder? Usually we create a `hooks` folder and add all custom hooks to that folder.

2021-06-14 09:23 UTC, macfrei commented on src/App.js
> +        <CreatePage onGoBack={handleGoBack} onSubmit={handleCreatePage} />
```suggestion
        <CreatePage onGoBack={() => setCurrentPage('usersPage')} onSubmit={handleCreatePage} />
```

2021-06-14 09:23 UTC, macfrei commented on src/App.js
> +        <UsersPage users={users} goToCreatepage={handleGoToCreatePage} />
```suggestion
        <UsersPage users={users} goToCreatePage={() => setCurrentPage('createPage')} />
```

2021-06-14 09:23 UTC, macfrei commented on src/App.js
> +      <UsersPage users={userData} /> */}
Please delete unused code.

2021-06-14 09:23 UTC, macfrei commented on src/App.js
> +  }
Not necessarily needed, but it's okay. Added a few suggestions above.

2021-06-14 09:23 UTC, macfrei commented on src/components/Button.spec.js
> +  it('contains a text', async () => {
```suggestion
  it('contains a text', () => {
```

2021-06-14 09:23 UTC, macfrei commented on src/components/Button.spec.js
> +  it('calls onClick correctly', async () => {
```suggestion
  it('calls onClick correctly', () => {
```

2021-06-14 09:23 UTC, macfrei commented on src/components/Button.spec.js
> +  })
I like it!

2021-06-14 09:23 UTC, macfrei commented on src/components/Form.js
> +import styled from 'styled-components'
```suggestion
import styled from 'styled-components/macro'
```

2021-06-14 09:23 UTC, macfrei commented on src/pages/UsersPage.js
> +        <SingleEntry key={index}>
Please us the `id` as a key and not the index.

2021-06-14 09:23 UTC, macfrei commented on src/pages/CreatePage.js
> +  const ref = React.forwardRef()
What do you use this for?

2021-06-14 09:23 UTC, macfrei commented on src/components/Form.spec.js
> +describe('Form', () => {
I would add a test where you test that the prop `onSubmit` is called with the form data.

2021-06-14 09:23 UTC, macfrei commented on src/components/Form.js
> +    const skills = [skill1, skill2, skill3, skill4, skill5, skill6]
Are there fixed skills? So a user who has 7 skills can't add more? How about only having one input field for skills and the user can add multiple skills separated by comma? I think that would help to shorten this form and the complexity you have here.

2021-06-14 09:23 UTC, macfrei commented on src/components/Form.js
> +  skill6: yup.string(),
I think this should maybe be an array with strings so that it's not limited to 6 skills. I commented on your submit function how to do it.

2021-06-14 09:23 UTC, macfrei commented on src/components/Form.js
> +      {errors.name && 'Name is required'}
Maybe add a styled error component which is in a different color or something like that and display the error messages with that.
```suggestion
      {errors.name && <Error>Name is required</Error>}
```

2021-06-14 09:23 UTC, macfrei commented on src/components/Form.js
> +        role="input"
Don't need the `role` as you semantically correct use an `input` element.

2021-06-14 09:23 UTC, macfrei commented on src/components/Form.js
> +        label="name:"
```suggestion
        labelText="Name:"
```

2021-06-14 09:23 UTC, macfrei commented on src/components/Form.js
> +        role="input"
Same as above for all input elements...

2021-06-14 09:23 UTC, macfrei commented on src/components/InputField.js
> +export default function InputField({ label, ...inputProps }) {
Personal preference: I think `labelText` would be a better name.
```suggestion
export default function InputField({ labelText, ...inputProps }) {
```

2021-06-14 09:23 UTC, macfrei commented on src/components/InputField.stories.js
> +  Default.args = {}
Add some props especially the text for the `label`

2021-06-15 09:39 UTC, roscha80 commented
All resolved

2021-06-15 10:12 UTC, merged